language: php
php:
  - 7.4
  - 7.2
  - hhvm

before_script:
 - composer install

script: 
  - mkdir -p build/logs
  - vendor/bin/phpunit -c ./phpunit.xml --coverage-clover build/logs/clover.xml ./tests

after_script:
 - php vendor/bin/coveralls -v
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml